python-poetry/website

- .pre-commit-config.yaml
- themes/poetry/layouts/shortcodes/tab.html
- themes/poetry/layouts/shortcodes/tabs.html
The prettier hook was broken after adding `additional_dependencies` since that's used to actually install prettier
> pre-commit: fix prettier

- .github/workflows/deploy-preview.yml
This change should, in theory, be enough to have comments in pull requests whenever there's a deployment :crossed_fingers:
> chore(ci): comment on PR on deploy

- Makefile
- package.json
Add [`--failAfterWarnings`](https://rollupjs.org/guide/en/#--failafterwarnings) to rollup so build errors will fail the deploy next time
Also includes a small tweak for fixing `make site` on a clean checkout. Currently, hugo will fail to start before rollup is finished building `assets/assets/app.js` and never try to restart
> ci: fail deployment on rollup errors

- themes/poetry/layouts/partials/documentation_flyover.html
Documentation header flyover doesn't load menu based on the selected version, meaning that links for `1.1` are loaded when selecting `master`.
This PR fixes that by loading the links accordingly to the version selected, if there is one, otherwise we default to the stable version of the documentation.
> fix(header): use version to load links

- README.md
The node version in the README is out-of-date -- replacing version 14 with version 16.
> fix: update node version readme

- src/css/_content.css
- themes/poetry/layouts/blog/list.html
- themes/poetry/layouts/categories/list.html
- themes/poetry/layouts/tags/baseof.html
- themes/poetry/layouts/tags/list.html
There are 3 paginated lists in the blog:
- blog posts
- categories
- tags
All of them handle pagination already, but the pagination is not displayed, as can be seen [here](https://python-poetry.org/blog/) for instance.
Documentation from Hugo about the pagination: https://gohugo.io/templates/pagination/#build-the-navigation
Also added https://github.com/python-poetry/website/commit/794d373398da6ba9404d9254425d38b1817530a0 to handle dark mode in tags pages, since [this is not the case](https://python-poetry.org/blog/tag/1.1/) today.
> Add pagination in blog + handle dark mode in tags pages

- content/blog/2022-08-22-announcing-poetry-1-1-15.md
- content/blog/2022-08-23-announcing-poetry-1-2-0rc1.md
- content/history.md
Announce Poetry `1.2.0rc1` and update `1.1.15` announcement to mention compatibility with `1.2` and future releases.
Also add missing changelogs for `1.2.0b2` and `1.2.0b3`.
> Add Poetry `1.2.0rc1` announcement

- .github/workflows/deploy-preview.yml
Avoid concurrent builds on PRs by adding `concurrency`.
> chore(ci): add concurrency to avoid concurrent doc preview builds

- Makefile
- README.md
- bin/website
- package-lock.json
- package.json
- tailwind.config.js
This streamlines developing docs locally by optionally symlinking `content/docs` rather than copying via
```
make site POETRY_REPO=../poetry
```
Suggested in #48
> feat: support symlinked docs for local dev

- pyproject.toml
Requires https://github.com/python-poetry/poetry/issues/5586.
Add `1.2` documentation to the website, which will become the default version displayed.
I've kept `1.1` since users could still need it during the transition phase.
It might be a good rule to always keep the 2 latest stable versions in the documentation from now on.
> chore: default stable documentation to `1.2`

- bin/website
Un-break the docs by building `/docs/1.2` and `/docs` from the same source, in parallel
> Fix build by building version-level and top-level docs in parallel

- src/js/controllers/clipboard_controller.js
- themes/poetry/layouts/shortcodes/clipboard.html
Thinking more about #84, it's probably easier to just automatically add a clipboard button to every codeblock rather than having to manually wrap each one in a `{{% clipboard %}} ... {{% /clipboard %}}` tag.
> feat: add new clipboard button to all code blocks

- .flake8
- .github/workflows/deploy-preview.yml
- .github/workflows/deploy-production.yml
- .pre-commit-config.yaml
- README.md
- bin/website
- package-lock.json
- package.json
- poetry.lock
- pyproject.toml
- Require Python >= 3.10 and Node >= 18, now that python-poetry/poetry#6391 and its 1.2 counterpart in python-poetry/poetry#6392 are merged
- Bump GH actions, `cleo`, and remove `black` and `isort` (they are only used through pre-commit, AFAIK)
Actions changelogs:
- [actions/checkout](https://github.com/actions/checkout/releases)
- [amondnet/vercel-action](https://github.com/amondnet/vercel-action/releases)
- [bobheadxi/deployments](https://github.com/bobheadxi/deployments/releases)
- `env` is now always required since [v1.0.0](https://github.com/bobheadxi/deployments/releases/tag/v1.0.0)
- [setup-python](https://github.com/actions/setup-python/releases)
> Require Python >= 3.10, Node >= 18 and bump GitHub actions

- package-lock.json
Broke the deployment in https://github.com/python-poetry/website/pull/80, looks like I needed to `npm install` instead of `npm update` :shrug:
> Correctly lock npm dependencies

- .github/workflows/deploy-production.yml
The entire site is currently blocked by hitting Algolia free tier limits. We can revert this later if desired, but until then we need to deploy even if we get an error back.
> fix: don't fail the entire build if building the search index fails

- content/blog/2023-05-19-announcing-poetry-1-5-0.md
- content/history.md
keep changelog in sync, cf python-poetry/poetry#7958
> chore: rephrase changelog entry to avoid ambiguity

- .github/workflows/deploy-preview.yml
The `push` trigger does not seem to work. The `pull_request` trigger should do.
Motivation: #159 fails because it needs a new hugo version, which has to be specificied in the workflow itself.
> ci: update workflow to allow to test workflow changes

- .github/workflows/deploy-preview.yaml
- .github/workflows/deploy-production.yaml
- layouts/partials/documentation_flyover.html
- layouts/partials/scripts.html
- layouts/partials/stylesheets.html
- package-lock.json
- package.json
- vercel.json
`.Site.IsServer` caused a deprecation warning.
`-v` was deprecated in [0.114.0](https://github.com/gohugoio/hugo/releases/tag/v0.114.0) and later removed.
The need for `plainify` is explained in https://github.com/gohugoio/hugo/releases/tag/v0.134.0
> chore: update hugo

- .github/workflows/deploy-preview.yaml
- .github/workflows/deploy-production.yaml
As proposed in [python-poetry/poetry#9879](https://github.com/python-poetry/poetry/pull/9879#discussion_r1863846110)
> ci: use npm installed hugo to reduce the number of hard-coded hugo versions

- package-lock.json
- package.json
- rollup.config.mjs
The relevant change for us is documented here: https://rollupjs.org/migration/#using-configuration-files
We must either add `"type": "module"` in our `package.json` or rename the rollup.config to `.mjs`. The first option does not work well because we have other CommonJS files. Therefore, I chose the second option.
Further, `__dirname` is not supported anymore and has to be replaced: https://rollupjs.org/command-line-interface/#getting-the-current-directory
> chore: update rollup

- .github/workflows/deploy-production.yaml
Building the search index fails since the `hugo` update in #159:
- last successful run: https://github.com/python-poetry/website/actions/runs/12076967191
- first failure: https://github.com/python-poetry/website/actions/runs/12082967521
The failure is caused by `hugo-bin` (since `v0.102.0`) removing the `vendor` directory, which is created by `bundle install` while setting up ruby, during installation: https://github.com/fenneclab/hugo-bin/compare/v0.101.5...v0.102.0
The following runs of a temporarily changed `Deploy Preview` workflow show that this PR fixes the issue (the index is normally only built in the `Deploy Production` workflow):
- without fix: https://github.com/python-poetry/website/actions/runs/12569633498
- with fix: …
> ci: fix building the search index

- content/blog/2025-01-11-announcing-poetry-2-0-1.md
- content/history.md
TODO:
* <strike>[ ] Write about highlights (if any)</strike>
> blog: announce Poetry 2.0.1
